services:
  api:
    container_name: DnD-Character-Manager-API
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: pyproject.toml

  db:
    container_name: DnD-Character-Manager-DB
    image: postgres:17.9
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  emailer:
    container_name: DnD-Character-Manager-Emailer
    image: maildev/maildev
    environment:
      TZ: Europe/Moscow
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
    restart: on-failure
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data:
