"""add character backgrounds and races

Revision ID: 5b567df35e2d
Revises: eb92e8ea2258
Create Date: 2026-04-16 19:44:08.811422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b567df35e2d'
down_revision: Union[str, Sequence[str], None] = 'eb92e8ea2258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backgrounds')),
    sa.UniqueConstraint('name', name=op.f('uq_backgrounds_name'))
    )
    op.create_table('races',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    sa.UniqueConstraint('name', name=op.f('uq_races_name'))
    )
    op.create_unique_constraint(op.f('uq_character_stats_character_id'), 'character_stats', ['character_id'])
    op.add_column('characters', sa.Column('race_id', sa.Uuid(), nullable=True))
    op.add_column('characters', sa.Column('background_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_characters_background_id_backgrounds'), 'characters', 'backgrounds', ['background_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_characters_race_id_races'), 'characters', 'races', ['race_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_characters_race_id_races'), 'characters', type_='foreignkey')
    op.drop_constraint(op.f('fk_characters_background_id_backgrounds'), 'characters', type_='foreignkey')
    op.drop_column('characters', 'background_id')
    op.drop_column('characters', 'race_id')
    op.drop_constraint(op.f('uq_character_stats_character_id'), 'character_stats', type_='unique')
    op.drop_table('races')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
